# Generated by Django 5.0.2 on 2024-03-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration_pg',
            new_name='Registration_pgs',
        ),
    ]
