# Generated by Django 5.0.2 on 2024-03-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0002_rename_registration_pg_registration_pgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_pgs',
            name='Registration_id',
            field=models.CharField(max_length=20),
        ),
    ]
