# Generated by Django 5.0.2 on 2024-03-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0003_alter_registration_pgs_registration_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations_pgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registration_id', models.CharField(max_length=20)),
                ('Full_name', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=50)),
                ('Mobile_number', models.CharField(max_length=10)),
                ('sharing_person', models.CharField(max_length=25, null=True)),
                ('price_person', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration_pgs',
        ),
    ]
